new setings

diff --git a/.config/i3/i3blocks/battery b/.config/i3/i3blocks/battery
--- a/.config/i3/i3blocks/battery
+++ b/.config/i3/i3blocks/battery
@@ -1,74 +1,31 @@
-#!/usr/bin/perl
-#
-# Copyright 2014 Pierre Mavro <deimos@deimos.fr>
-# Copyright 2014 Vivien Didelot <vivien@didelot.org>
-#
-# Licensed under the terms of the GNU GPL v3, or any later version.
-#
-# This script is meant to use with i3blocks. It parses the output of the "acpi"
-# command (often provided by a package of the same name) to read the status of
-# the battery, and eventually its remaining time (to full charge or discharge).
-#
-# The color will gradually change for a percentage below 85%, and the urgency
-# (exit code 33) is set if there is less that 5% remaining.
+#!/bin/bash
 
-use strict;
-use warnings;
-use utf8;
+BAT_PATH="/sys/class/power_supply/BAT0"
 
-my $acpi;
-my $status;
-my $percent;
-my $full_text;
-my $short_text;
-my $bat_number = $ENV{BLOCK_INSTANCE} || 0;
+if [[ ! -d "$BAT_PATH" ]]; then
+    echo "bat not found"
+    exit 1
+fi
 
-# read the first line of the "acpi" command output
-open (ACPI, "acpi -b | grep 'Battery $bat_number' |") or die;
-$acpi = <ACPI>;
-close(ACPI);
+if [[ ! -f "$BAT_PATH/status" ]] || [[ ! -f "$BAT_PATH/capacity" ]]; then
+    echo "bat info missing"
+    exit 1
+fi
 
-# fail on unexpected output
-if ($acpi !~ /: (\w+), (\d+)%/) {
-	die "$acpi\n";
-}
+status=$(cat "$BAT_PATH/status")
+capacity=$(cat "$BAT_PATH/capacity")
 
-$status = $1;
-$percent = $2;
-$full_text = "$percent%";
+status_lower=$(echo "$status" | tr '[:upper:]' '[:lower:]')
 
-if ($status eq 'Discharging') {
-	$full_text .= ' dis';
-} elsif ($status eq 'Charging') {
-	$full_text .= ' chr';
-}
+if [[ "$status_lower" == "discharging" ]]; then
+    state="dis"
+elif [[ "$status_lower" == "charging" ]]; then
+    state="chr"
+elif [[ "$status_lower" == "full" || "$status_lower" == "not charging" || "$capacity" -ge 100 ]]; then
+    state="full"
+else
+    state="unk"
+fi
 
-$short_text = $full_text;
+echo "$capacity%-$state"
 
-if ($acpi =~ /(\d\d:\d\d):/) {
-	$full_text .= " ($1)";
-}
-
-# print text
-print "$full_text\n";
-print "$short_text\n";
-
-# consider color and urgent flag only on discharge
-if ($status eq 'Discharging') {
-
-	if ($percent < 20) {
-		print "";
-	} elsif ($percent < 40) {
-		print "";
-	} elsif ($percent < 60) {
-		print "";
-	} elsif ($percent < 85) {
-		print "";
-	}
-
-	if ($percent < 5) {
-		exit(33);
-	}
-}
-
-exit(0);
